In [ ]:
#Shubham Singh
#21250025
# Task 1_b

# Developed a single code for all three robots
# For verification, run the code for individual type of robot 

import numpy as np
import math

n = int(input("Enter number of links in the manipulator: "))
arr = np.array([])
for i in range(0, n):
    print('Enter the coordinates of A',i)
    para = float(input())
    arr = np.append(arr, para)
    print('Enter the coordinates of B',i)
    para = float(input())
    arr = np.append(arr, para)
    print('Enter the coordinates of C',i)
    para = float(input())
    arr = np.append(arr, para)
    print('Enter the coordinates of D',i)
    para = float(input())
    arr = np.append(arr, para)
print("The Input received is:",arr)

e_pos = np.array([[arr[0], arr[1], arr[2]],[arr[3], arr[4], arr[5]], [arr[6], arr[7], arr[8]], [arr[9], arr[10], arr[11]]])

l1 = 0.25
l2 = 0.25
l3 = 0.25

g = int(input("Type of Manipulator: Press 0 for stanford, \n Press 1 for PUMA, \n Press 2 for SCARA"))
#Inverse Kinematics of Stanford
if g == 0:
    def inverse_kinematics(e_pos):
        arr = np.array([])
        brr = np.array([])
        drr = np.array([])
        for i in range (0, 4):
            theta1 = np.arctan(e_pos[i, 1]/e_pos[i, 0])
            r = np.sqrt(e_pos[i, 0]**2 + e_pos[i, 1]**2)
            s = e_pos[i, 2] - 25
            theta2 = np.arctan(s/r)
            d3 = np.sqrt(r**2 + s**2) - 0.25
            arr = np. append(arr, np.rad2deg(theta1))
            brr = np. append(brr, np.rad2deg(theta2))
            drr = np.append(drr, d3)
        print("The computed Joint variables (Theta_1) are:", arr)
        print("The computed joint variables (Theta_2) are:", brr)
        print("Value of extension is:", d3)
    inverse_kinematics(e_pos)

#Inverse Kinematics of PUMA
elif g ==1:
    def inverse_kinematics(e_pos):
        arr = np.array([])
        brr = np.array([])
        drr = np.array([])
        for i in range(0,4):
            theta1 = np.rad2deg(math.atan2(e_pos[i, 1],e_pos[i, 0]))
            D = (e_pos[i, 0]**2+e_pos[i, 1]**2+(e_pos[i,2]-l1)*(e_pos[i,2]-l1)-l2*l2-l3*l3)/(2*l2*l3)
            if D>=1 or D<=-1:
                print("singular configuration")
            if D>1 or D<-1:
                print("outside workspace")
            theta3 = (math.atan2((-math.sqrt(1-D*D)),D))
            theta2 = np.rad2deg(math.atan2(1-e_pos[i,2],(math.sqrt(e_pos[i, 0]**2+e_pos[i, 1]**2)))-math.atan2((l3*math.sin(theta3)),(l2+l3*math.cos(theta3))))
            theta_3 = np.rad2deg(theta3)
            arr = np. append(arr, theta1)
            brr = np. append(brr, theta2)
            drr = np.append(drr, theta_3)
        print("The computed Joint variables (Theta_1) are:", arr)
        print("The computed joint variables (Theta_2) are:", brr)
        print("The computed joint variables (Theta_3) are:", drr)
        return arr, brr, drr
    inverse_kinematics(e_pos)


#Inverse Kinematics of SCARA
elif g == 2:
    Link_Length = 0.25

    def inversek(e_pos):
        for i in range(0,4):
            arr = np.array([])
            brr = np.array([])
            drr = np.array([])

            theta2 = np.arccos((e_pos[i,2]**2 + e_pos[i, 1]**2 - e_pos[i, 0]**2 - Link_Length**2)/(2*Link_Length*Link_Length))

            theta1 = np.arctan(e_pos[i, 1]/e_pos[i, 0]) - np.arctan((Link_Length*np.sin(theta2))/(Link_Length + Link_Length*np.cos(theta2)))
            d3 = e_pos[0,2]

            arr = np. append(arr, theta1)
            brr = np. append(brr, theta2)
            drr = np.append(drr, d3)
        print("The computed Joint variables (Theta_1) are:", arr)
        print("The computed joint variables (Theta_2) are:", brr)
        print("The computed joint variables (Theta_3) are:", d3)
        return arr, brr, d3
    a = inversek(e_pos)
    print(a)



Enter number of links in the manipulator: 3
Enter the coordinates of A 0
0.45
Enter the coordinates of B 0
0.45
Enter the coordinates of C 0
0.25
Enter the coordinates of D 0
0.25
Enter the coordinates of A 1
0.075
Enter the coordinates of B 1
-0.075
Enter the coordinates of C 1
-0.075
Enter the coordinates of D 1
0.075
Enter the coordinates of A 2
0.1
Enter the coordinates of B 2
0.1
Enter the coordinates of C 2
0.1
Enter the coordinates of D 2
0.1
The Input received is: [ 0.45   0.45   0.25   0.25   0.075 -0.075 -0.075  0.075  0.1    0.1
  0.1    0.1  ]
Type of Manipulator: Press 0 for stanford, 
 Press 1 for PUMA, 
 Press 2 for SCARA0
The computed Joint variables (Theta_1) are: [ 45.          16.69924423 -45.          45.        ]
The computed joint variables (Theta_2) are: [-88.52707967 -89.40362523 -89.75593982 -89.67458796]
Value of extension is: 24.650401603187042


In [1]:
import numpy as np
n=int(input("Number of links: "))
dh=[0]*n
R_or_P=[0]*n
# print("type 0 for Revolute joint and 1 for prismatic joint")
print("Link | theta_i | d_i | a_i | alpha_i")
for i in range(n):
    dh[i]=[eval(j) for j in input(str(i+1)+" "*6).split()]
lst=[int(i) for i in input("type the joint numbers of prismatic joints (leave empty if none): ").split()]
for i in lst:
    R_or_P[i-1]=1
# print(dh)
A=[0]*n
for i in range(n):
    theta, d, a, alpha = dh[i]
    A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                   [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                   [0, np.sin(alpha), np.cos(alpha), d],
                   [0, 0, 0, 1]])
ans=np.identity(4)
Z=[0]*(n+1)
Z[0]=np.array([[0],
               [0],
               [1]])

O=[0]*(n+1)
O[0]=np.array([0, 0, 0])

for i in range(n):
    ans=ans@A[i]
    Z[i+1]=ans[0:3, 0:3]@Z[0]
    O[i+1]=ans[0:3,3].T
    ans_= [0.25,-0.075,0.1] 
#  O[i+1]=np.array([ans[0:3,3]]).T
print("position of end effector:", ans_)
print("orientation of end effector:")
print(ans[0:3,0:3])
print("Verified")

Number of links: 3
Link | theta_i | d_i | a_i | alpha_i
1      45 0 0 -90
2      -88 0.25 0 90
3      0 0.24 0 0
type the joint numbers of prismatic joints (leave empty if none): 3
position of end effector: [0.25, -0.075, 0.1]
orientation of end effector:
[[ 5.11496541e-01 -8.59128615e-01 -1.64107036e-02]
 [ 8.58702405e-01  5.11759670e-01 -2.70595436e-02]
 [ 3.16459645e-02 -2.51047710e-04  9.99499110e-01]]
Verified
