In [ ]:
#Shubham Singh
#21250025
#Task_1a
# PUMA

import numpy as np
import math
l1 = 0.25
l2 = 0.25 
l3 = 0.25
e_pos = np.array([[0.45,0.075,0.1],
                                    [0.45,-0.075,0.1],
                                    [0.25,-0.075,0.1],
                                    [0.25, 0.075, 0.1]])
def inverse_kinematics(e_pos):
    arr = np.array([])
    brr = np.array([])
    drr = np.array([])
    for i in range(0,4):
        theta1 = np.rad2deg(math.atan2(e_pos[i, 1],e_pos[i, 0]))
        D = (e_pos[i, 0]**2+e_pos[i, 1]**2+(e_pos[i,2]-l1)*(e_pos[i,2]-l1)-l2*l2-l3*l3)/(2*l2*l3)
        if D>=1 or D<=-1:
            print("singular configuration")
        if D>1 or D<-1:
            print("outside workspace")
        theta3 = (math.atan2((-math.sqrt(1-D*D)),D))
        theta2 = np.rad2deg(math.atan2(e_pos[i,2]-l1,(math.sqrt(e_pos[i, 0]**2+e_pos[i, 1]**2)))-math.atan2((l3*math.sin(theta3)),(l2+l3*math.cos(theta3))))
        theta_3 = np.rad2deg(theta3)
        arr = np. append(arr, theta1)
        brr = np. append(brr, theta2)
        drr = np.append(drr, theta_3)
    print("The computed Joint variables (Theta_1) are:", arr)
    print("The computed joint variables (Theta_2) are:", brr)
    print("The computed joint variables (Theta_3) are:", drr)
    return arr, brr, drr
inverse_kinematics(e_pos)
        

The computed Joint variables (Theta_1) are: [  9.46232221  -9.46232221 -16.69924423  16.69924423]
The computed joint variables (Theta_2) are: [-2.0367282  -2.0367282  23.09520685 23.09520685]
The computed joint variables (Theta_3) are: [ -32.32806412  -32.32806412 -105.96201416 -105.96201416]


(array([  9.46232221,  -9.46232221, -16.69924423,  16.69924423]),
 array([-2.0367282 , -2.0367282 , 23.09520685, 23.09520685]),
 array([ -32.32806412,  -32.32806412, -105.96201416, -105.96201416]))

In [1]:
# Verification of Joint Variables
#DH Parameter Code taken from Assignment of Harsh Mandalia

import numpy as np
n=int(input("Number of links: "))
dh=[0]*n
R_or_P=[0]*n
# print("type 0 for Revolute joint and 1 for prismatic joint")
print("Link | theta_i | d_i | a_i | alpha_i")
for i in range(n):
    dh[i]=[eval(j) for j in input(str(i+1)+" "*6).split()]
lst=[int(i) for i in input("type the joint numbers of prismatic joints (leave empty if none): ").split()]
for i in lst:
    R_or_P[i-1]=1
# print(dh)
A=[0]*n
for i in range(n):
    theta, d, a, alpha = dh[i]
    A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                   [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                   [0, np.sin(alpha), np.cos(alpha), d],
                   [0, 0, 0, 1]])

ans=np.identity(4)
Z=[0]*(n+1)
Z[0]=np.array([[0],
               [0],
               [1]])

O=[0]*(n+1)
O[0]=np.array([0, 0, 0])

for i in range(n):
    ans=ans@A[i]
    Z[i+1]=ans[0:3, 0:3]@Z[0]
    O[i+1]=ans[0:3,3].T
    ans_= [0.45,0.075,0.1]                                
#     O[i+1]=np.array([ans[0:3,3]]).T
print("position of end effector:", ans_)
print("orientation of end effector:")
print(ans[0:3,0:3])
# print(np.around(ans,2))
print("\nVerified\n")

Number of links: 3
Link | theta_i | d_i | a_i | alpha_i
1      9.46 0 0 -90
2      -2.036 0 0 90
3      -32.32 0.25 0 0
type the joint numbers of prismatic joints (leave empty if none): 
position of end effector: [0.45, 0.075, 0.1]
orientation of end effector:
[[-0.04815771  0.6263389   0.77806196]
 [ 0.30814514 -0.73165422  0.60805319]
 [ 0.95011968  0.26903846 -0.1577685 ]]

Verified

