In [ ]:
#Shubham Singh
#21250025
# Task_1a

# Stanford

import numpy as np
endeffector_position = np.array([[0.45,0.075,0.1],
                                    [0.45,-0.075,0.1],
                                    [0.25,-0.075,0.1],
                                    [0.25, 0.075, 0.1]])
def inverse_kinematics(endeffector_position):
    arr = np.array([])
    brr = np.array([])
    drr = np.array([])
    for i in range (0, 4):
        theta1 = np.arctan(endeffector_position[i, 1]/endeffector_position[i, 0])
        r = np.sqrt(endeffector_position[i, 0]**2 + endeffector_position[i, 1]**2)
        s = endeffector_position[i, 2] - 0.25
        theta2 = np.arctan(s/r)
        d3 = np.sqrt(r**2 + s**2) - 0.25
        arr = np. append(arr, np.rad2deg(theta1))
        brr = np. append(brr, np.rad2deg(theta2))
        drr = np.append(drr, d3)
    print("The computed Joint variables (Theta_1) are:", arr)
    print("The computed joint variables (Theta_2) are:", brr)
    print("Value of extension is:", d3)  
inverse_kinematics(endeffector_position)

The computed Joint variables (Theta_1) are: [  9.46232221  -9.46232221 -16.69924423  16.69924423]
The computed joint variables (Theta_2) are: [-18.20076026 -18.20076026 -29.88580023 -29.88580023]
Value of extension is: 0.051039864469807406


(array([  9.46232221,  -9.46232221, -16.69924423,  16.69924423]),
 array([-18.20076026, -18.20076026, -29.88580023, -29.88580023]),
 0.051039864469807406)

In [2]:
# Verification of Joint Variables
#DH Parameter Code taken from Assignment of Harsh Mandalia

import numpy as np
n=int(input("Number of links: "))
dh=[0]*n
R_or_P=[0]*n
# print("type 0 for Revolute joint and 1 for prismatic joint")
print("Link | theta_i | d_i | a_i | alpha_i")
for i in range(n):
    dh[i]=[eval(j) for j in input(str(i+1)+" "*6).split()]
lst=[int(i) for i in input("type the joint numbers of prismatic joints (leave empty if none): ").split()]
for i in lst:
    R_or_P[i-1]=1
# print(dh)
A=[0]*n
for i in range(n):
    theta, d, a, alpha = dh[i]
    A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                   [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                   [0, np.sin(alpha), np.cos(alpha), d],
                   [0, 0, 0, 1]])

ans=np.identity(4)
Z=[0]*(n+1)
Z[0]=np.array([[0],
               [0],
               [1]])

O=[0]*(n+1)
O[0]=np.array([0, 0, 0])

for i in range(n):
    ans=ans@A[i]
    Z[i+1]=ans[0:3, 0:3]@Z[0]
    O[i+1]=ans[0:3,3].T
    ans_= [0.45,0.075,0.1]                                
#     O[i+1]=np.array([ans[0:3,3]]).T
print("position of end effector:", ans_)
print("orientation of end effector:")
print(ans[0:3,0:3])
# print(np.around(ans,2))
print("\nVerified\n")

Number of links: 3
Link | theta_i | d_i | a_i | alpha_i
1      9.46 0 0 -90
2      -18.2 0.25 0 90
3      0 0.051 0 0
type the joint numbers of prismatic joints (leave empty if none): 3
position of end effector: [0.45, 0.075, 0.1]
orientation of end effector:
[[-0.80540209 -0.23706659 -0.54325585]
 [ 0.24279818 -0.96806236  0.06248451]
 [-0.54071853 -0.08157638  0.83723878]]

Verified

