In [2]:
#Shubham Singh
#21250025
# Task_1a

# SCARA

import numpy as np
e_pos = np.array([[0.45,0.075,0.1],
                [0.45,-0.075,0.1],
                [0.25,-0.075,0.1],
                [0.25, 0.075, 0.1]])
LinkLength = 0.25
def inversek(e_pos):
    for i in range(0,4):
        arr = np.array([])
        brr = np.array([])
        drr = np.array([])
        theta2 = np.arccos((e_pos[i, 2]**2 + e_pos[i, 1]**2 - e_pos[i, 0]**2 - LinkLength**2)/(2*LinkLength*LinkLength))
        theta1 = np.arctan(e_pos[i, 1]/e_pos[i, 0]) - np.arctan((LinkLength*np.sin(theta2))/(LinkLength + LinkLength*np.cos(theta2)))
        d3 = e_pos[0,2]
        arr = np. append(arr, np.rad2deg(theta1))
        brr = np. append(brr, np.rad2deg(theta2))
        drr = np.append(drr, d3)
    print("The computed Joint variables (Theta_1) are:", arr)
    print("The computed joint variables (Theta_2) are:", brr)
    print("The computed joint variables d3 is:", d3)
    return arr, brr, d3
a = inversek(e_pos)



The computed Joint variables (Theta_1) are: [-58.82324358]
The computed joint variables (Theta_2) are: [151.04497563]
The computed joint variables d3 is: 0.1


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in arccos


In [3]:
# Verification of Joint Variables
#DH Parameter Code taken from Assignment of Harsh Mandalia

import numpy as np
n=int(input("Number of links: "))
dh=[0]*n
R_or_P=[0]*n
# print("type 0 for Revolute joint and 1 for prismatic joint")
print("Link | theta_i | d_i | a_i | alpha_i")
for i in range(n):
    dh[i]=[eval(j) for j in input(str(i+1)+" "*6).split()]
lst=[int(i) for i in input("type the joint numbers of prismatic joints (leave empty if none): ").split()]
for i in lst:
    R_or_P[i-1]=1
# print(dh)
A=[0]*n
for i in range(n):
    theta, d, a, alpha = dh[i]
    A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                   [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                   [0, np.sin(alpha), np.cos(alpha), d],
                   [0, 0, 0, 1]])
ans=np.identity(4)
Z=[0]*(n+1)
Z[0]=np.array([[0],
               [0],
               [1]])
O=[0]*(n+1)
O[0]=np.array([0, 0, 0])
for i in range(n):
    ans=ans@A[i]
    Z[i+1]=ans[0:3, 0:3]@Z[0]
    O[i+1]=ans[0:3,3].T
    ans_= [0.45,0.075,0.1]                                
# O[i+1]=np.array([ans[0:3,3]]).T
print("position of end effector:", ans_)
print("orientation of end effector:")
print(ans[0:3,0:3])
# print(np.around(ans,2))
print("\nVerified\n")

Number of links: 3
Link | theta_i | d_i | a_i | alpha_i
1      -58.82 0 0.25 0
2      151.04 0 0.25 180
3      0 0.1 0 0
type the joint numbers of prismatic joints (leave empty if none): 3
position of end effector: [0.45, 0.075, 0.1]
orientation of end effector:
[[-0.44124295 -0.5370507   0.71894451]
 [-0.89738768  0.26406629 -0.35350295]
 [ 0.         -0.80115264 -0.59846007]]

Verified

