In [ ]:
import numpy as np
import math

In [ ]:
# scara
def scara_invkin(x,y,z,d1,d2):
    # using formulae from the textbook
    r = abs((x**2+y**2-d1**2-d2**2)/(2*d1*d2))
    theta2 = np.arctan(np.sqrt(abs(1-r**2))/r)
    theta1 = np.arctan(y/x) - np.arctan((d2*np.sin(theta2))/(d1+d2*np.cos(theta2)))
    d3 = -z
    # converting from radians to degrees
    theta1_deg = theta1*180/np.pi
    theta2_deg = theta2*180/np.pi
    print(f"theta1 = {theta1_deg} deg")
    print(f"theta2 = {theta2_deg} deg")
    return theta1, theta2

In [ ]:
# standford
def inverse_kinematics(endeffector_position,lengthsoflinks):
    theta1 = np.arctan(endeffector_position[1]/endeffector_position[0])
    r = np.sqrt(endeffector_position[0]**2 + endeffector_position[1]**2)
    s = endeffector_position[2] - lengthsoflinks[0]
    theta2 = np.arctan(s/r)
    d3 = np.sqrt(r**2 + s**2) - lengthsoflinks[1]
    print("First Solution: \n", "Theta1 = ", theta1, "\n Theta2 =", theta2,"\n Extension: ", d3, "\n")
    print("Second Solution: \n", "Theta1 = ", np.pi + theta1, "\n Theta2 =", np.pi - theta2,"\n Extension:", d3)
    return theta1, theta2,d3

In [ ]:
# Link Parameters:    [a, alpha, d, theta]
# For Multiple Links: [[a, alpha, d, theta]
#                      [a, alpha, d, theta]
#                      [a, alpha, d, theta]]

def atransformation(LinkParameters):
    a = LinkParameters[0]
    d = LinkParameters[2]
    alpha = LinkParameters[1]
    theta = LinkParameters[3]
    A = np.array([[[np.cos(theta), -np.sin(theta) * np.cos(alpha), np.sin(theta) * np.sin(alpha), a * np.cos(theta)],
                   [np.sin(theta), np.cos(theta) * np.cos(alpha), -np.cos(theta) * np.sin(alpha), a * np.sin(theta)],
                   [0, np.sin(alpha), np.cos(alpha), d],
                   [0, 0, 0, 1]]])
    return (A)


# Homogenous Matrices Forward Kinematics from DH
def forward_kinematics_homogenous_matrix(DH):
    A = np.identity(4)
    n = np.shape(DH)[0]

    for i in range(n):
        Anext = atransformation(DH[i])
        A = np.matmul(A,Anext)

    return A


##Inverse kinametics and forward kinematics computation for SCARA

In [ ]:
# joint variables for the block
a = (0.45, 0.075, 0.1)
b = (0.45, -0.75, 0.1)
c = (0.25, -0.075, 0.1)
d = (0.25, 0.75, 0.1)

# length of the links 
d1 = 0.25
d2 = 0.25

# joint angle for point a
print("joint angles for point A:")
theta1, theta2 = scara_invkin(a[0],a[1],a[2],d1, d2)

# DH parameters for joint angles at A
# a = 0
# d = 0
# alpha = 0
# theta = np.pi/4
# LinkParameters = [a, alpha, d, theta]
LinkParameters = [[0.25, np.pi/2, 0, theta1],[0.25, -np.pi/2, 0, theta2]]
T = forward_kinematics_homogenous_matrix(LinkParameters)
print("Final transformation matrix: ")
print(T)

# joint angle for point b
print("\njoint angles for point B:")
theta1, theta2 = scara_invkin(b[0],b[1],b[2],d1, d2)
LinkParameters = [[0.25, np.pi/2, 0, theta1],[0.25, -np.pi/2, 0, theta2]]
T = forward_kinematics_homogenous_matrix(LinkParameters)
print("Final transformation matrix: ")
print(T)

# joint angle for point c
print("\njoint angles for point C:")
theta1, theta2 = scara_invkin(c[0],c[1],c[2],d1, d2)
LinkParameters = [[0.25, np.pi/2, 0.2, theta1],[0.25, -np.pi/2, 0, theta2]]
T = forward_kinematics_homogenous_matrix(LinkParameters)
print("Final transformation matrix: ")
print(T)

# joint angle for point d
print("\njoint angles for point D:")
theta1, theta2 = scara_invkin(d[0],d[1],d[2],d1, d2)
LinkParameters = [[0.25, np.pi/2, 0, theta1],[0.25, -np.pi/2, 0, theta2]]
T = forward_kinematics_homogenous_matrix(LinkParameters)
print("Final transformation matrix: ")
print(T)



joint angles for point A:
theta1 = -14.696515095304628 deg
theta2 = 48.31767460666049 deg
Final transformation matrix: 
[[[ 6.43243318e-01  2.53699112e-01 -7.22409021e-01  4.02631626e-01]
  [-1.68709909e-01  9.67283185e-01  1.89473496e-01 -1.05602255e-01]
  [ 7.46843357e-01 -2.05128339e-17  6.65000000e-01  1.86710839e-01]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]]

joint angles for point B:
theta1 = -81.25770600178518 deg
theta2 = 44.44292506771737 deg
Final transformation matrix: 
[[[ 1.08513327e-01  9.88381961e-01 -1.06423476e-01  6.51259456e-02]
  [-7.05653624e-01  1.51990455e-01  6.92063483e-01 -4.23508896e-01]
  [ 7.00198415e-01 -1.75156148e-17  7.13948303e-01  1.75049604e-01]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]]

joint angles for point C:
theta1 = -48.166777119576935 deg
theta2 = 62.93506577116662 deg
Final transformation matrix: 
[[[ 3.03468903e-01  7.45089386e-01 -5.93926284e-01  2.42608381e-01]
  [-3.39015671e-01  6.6

##Inverse and forward kinematics for Standford

In [ ]:
# joint variables for the block
a = (0.45, 0.075, 0.1)
b = (0.45, -0.75, 0.1)
c = (0.25, -0.075, 0.1)
d = (0.25, 0.75, 0.1)

# length of the links 
length_of_links = (0.25, 0.25)

# joint angle for point a
print("joint angles for point A:")
theta1, theta2, d3 = inverse_kinematics(a,length_of_links)

# DH parameters for joint angles at A
# a = 0
# d = 0
# alpha = 0
# theta = np.pi/4
# LinkParameters = [a, alpha, d, theta]
LinkParameters = [[0, -np.pi/2, 0, theta1],[0, -np.pi/2, 0, theta2]]
T = forward_kinematics_homogenous_matrix(LinkParameters)
print("Final transformation matrix: ")
print(T)

# joint angle for point b
print("\njoint angles for point B:")
theta1, theta2, d3 = inverse_kinematics(b,length_of_links)
LinkParameters = [[0, np.pi/2, 0.25, theta1],[0, np.pi/2, 0.25, theta2]]
T = forward_kinematics_homogenous_matrix(LinkParameters)
print("Final transformation matrix: ")
print(T)

# joint angle for point c
print("\njoint angles for point C:")
theta1, theta2, d3 = inverse_kinematics(c,length_of_links)
LinkParameters = [[0, 0, d3, theta1],[0, 0, d3, theta2]]
T = forward_kinematics_homogenous_matrix(LinkParameters)
print("Final transformation matrix: ")
print(T)

# joint angle for point d
print("\njoint angles for point D:")
theta1, theta2, d3 = inverse_kinematics(d,length_of_links)
LinkParameters = [[0, -np.pi/2, 0, theta1],[0, -np.pi/2, 0, theta2]]
T = forward_kinematics_homogenous_matrix(LinkParameters)
print("Final transformation matrix: ")
print(T)



joint angles for point A:
First Solution: 
 Theta1 =  0.16514867741462683 
 Theta2 = -0.3176631929822606 
 Extension:  0.23023431780746362 

Second Solution: 
 Theta1 =  3.30674133100442 
 Theta2 = 3.4592558465720535 
 Extension: 0.23023431780746362
Final transformation matrix: 
[[[ 9.37042571e-01  1.64398987e-01  3.08097700e-01  0.00000000e+00]
  [ 1.56173762e-01 -9.86393924e-01  5.13496166e-02  0.00000000e+00]
  [ 3.12347524e-01 -1.19401098e-16 -9.49967907e-01  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]]

joint angles for point B:
First Solution: 
 Theta1 =  -1.0303768265243125 
 Theta2 = -0.16984628808367364 
 Extension:  0.6374119674649424 

Second Solution: 
 Theta1 =  2.1112158270654806 
 Theta2 = 3.3114389416734666 
 Extension: 0.6374119674649424
Final transformation matrix: 
[[[ 5.07092553e-01 -8.57492926e-01 -8.69656553e-02 -2.14373231e-01]
  [-8.45154255e-01 -5.14495755e-01  1.44942759e-01 -1.28623939e-01]
  [-1.69030851e-01  1.215835

###Inverse and forward kinematics for PUMA robot

In [ ]:
# inverse kinematics
def inverse_kinematics(l1,l2,l3,xc,yc,zc):
    theta1 = math.atan2(yc,xc)
    D = (xc*xc+yc*yc+(zc-l1)*(zc-l1)-l2*l2-l3*l3)/(2*l2*l3)
    if D>=1 or D<=-1:
        print("singular configuration")
  
    if D>1 or D<-1:
        print("outside workspace")
        
    theta3 = (math.atan2((-math.sqrt(1-D*D)),D))
    theta2 = math.atan2(zc-l1,(math.sqrt(xc*xc+yc*yc)))-math.atan2((l3*math.sin(theta3)),(l2+l3*math.cos(theta3)))
    print("Theta1 = ",np.rad2deg(theta1),"\nTheta2 = ", np.rad2deg(theta2), "\nTheta3 = ", np.rad2deg(theta3))
    return theta1,theta2,theta3

In [ ]:
# joint variables for the block
a = (0.45, 0.075, 0.1)
b = (0.45, -0.75, 0.1)
c = (0.25, -0.075, 0.1)
d = (0.25, 0.75, 0.1)

l1 = l2 = l3 = 0.25
print("Inverse Kinematics solution")
print("for coordinate A:")
theta1, theta2, theta3 = inverse_kinematics(l1, l2, l3, a[0], a[1], a[2])
print("\nforward kinematics solution")
#LinkParameters = [a, alpha, d, theta]
LinkParameters = [[0.25, 0, 0, theta1], [0.25, -np.pi/2, 0, theta2], [0, 0, 0, theta3]]
T = forward_kinematics_homogenous_matrix(LinkParameters)
print("Final transformation matrix: ")
print(T)



Inverse Kinematics solution
for coordinate A:
Theta1 =  9.462322208025617 
Theta2 =  -2.0367282034521836 
Theta3 =  -32.328064122162274

forward kinematics solution
Final transformation matrix: 
[[[ 8.37913433e-01  5.30281503e-01 -1.29238563e-01  4.94501864e-01]
  [ 1.09206586e-01  6.91124286e-02  9.91613530e-01  7.34093875e-02]
  [ 5.34766304e-01 -8.45000000e-01  6.12323400e-17  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]]


In [ ]:
print("\nfor coordinate B:")
theta1, theta2, theta3 = inverse_kinematics(l1, l2, l3, b[0], b[1], b[2])
print("\nforward kinematics solution")
#LinkParameters = [a, alpha, d, theta]
LinkParameters = [[0.25, 0, 0, theta1], [0.25, -np.pi/2, 0, theta2], [0, 0, 0, theta3]]
T = forward_kinematics_homogenous_matrix(LinkParameters)
print("Final transformation matrix: ")
print(T)


for coordinate B:
singular configuration
outside workspace


ValueError: ignored

In [ ]:
print("\nfor coordinate C:")
theta1, theta2, theta3 = inverse_kinematics(l1, l2, l3, c[0], c[1], c[2])
print("\nforward kinematics solution")
#LinkParameters = [a, alpha, d, theta]
LinkParameters = [[0.25, 0, 0, theta1], [0.25, -np.pi/2, 0, theta2], [0, 0, 0, theta3]]
T = forward_kinematics_homogenous_matrix(LinkParameters)
print("Final transformation matrix: ")
print(T)


for coordinate C:
Theta1 =  -16.69924423399362 
Theta2 =  23.09520684670464 
Theta3 =  -105.96201416284724

forward kinematics solution
Final transformation matrix: 
[[[-2.73288337e-01  9.55459978e-01 -1.11398905e-01  4.87900514e-01]
  [-3.06346990e-02  1.07103834e-01  9.93775771e-01 -4.39872450e-02]
  [ 9.61444226e-01  2.75000000e-01  6.12323400e-17  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]]


In [ ]:
print("\nfor coordinate D:")
theta1, theta2, theta3 = inverse_kinematics(l1, l2, l3, d[0], d[1], d[2])
print("\nforward kinematics solution")
#LinkParameters = [a, alpha, d, theta]
LinkParameters = [[0.25, 0, 0, theta1], [0.25, -np.pi/2, 0, theta2], [0, 0, 0, theta3]]
T = forward_kinematics_homogenous_matrix(LinkParameters)
print("Final transformation matrix: ")
print(T)



for coordinate D:
singular configuration
outside workspace


ValueError: ignored